### PR TITLE
Improve shooting control

### PR DESCRIPTION
**Pull request by wusyong**
Despite comment states marine should be static to shoot, it still has
a few bugs out there. This PR fix those bugs and make marine to shoot if
he is static for sure. Some condition checks are also removed since they
might not be needed to actually do the check. If users hold the action,
shooting state will be active only if the marine stop moving.

PS. I know I should do `cargo fmt` but it seems it's in another PR. Could I
just do it anyways?

### CODE REVIEW

**Comment by krankur** [comment]
@wusyong Thanks for finding and fixing the bug. Can you provide some more details about the bug, such as the steps to reproduce them? It would help with the review process.

> PS. I know I should do cargo fmt but it seems it's in another PR. Could I
just do it anyways?

Yes, please go ahead. The other PR is pretty old and inactive for a long time.

**Comment by wusyong** [comment]
@krankur Current marine will keep shooting animation (but with one bullet) if users hold shooting button. And If users hold shooting while moving, the marine will be stuck at the movement and animation. The shooting behavior after fix is what I describe above.

> Yes, please go ahead. The other PR is pretty old and inactive for a long time.

Thanks. I'm not on my computer atm. I will push format commit later tomorrow.

**Comment by erlend-sh** [comment]
Does this also close #23 ?

**Comment by krankur** [comment]
@erlend-sh Yes, this and other PRs cover the changes done in https://github.com/amethyst/space-menace/pull/23. Closed. Thanks.

**Pull request merged**
