### PR TITLE
Get code to compile against Amethyst 0.15.0

### PR DESCRIPTION
**Pull request by szunami**

### CODE REVIEW

**Comment by krankur** [comment]
@szunami thanks for the PR. This was long time pending.

**Comment by szunami** [comment]
Sure thing, happy to clean this up. I wasn't sure if this repo was still being maintained or not. I'll give it a try and see if I have any questions.

**Comment by szunami** [comment]
Also happy to regenerate the gif once the assets are aligned

**Comment by szunami** [comment]
@krankur I cleaned up the warnings. I'm a little confused about the asset scaling, as I'm not sure what changed about that. Any help?

**Comment by krankur** [comment]
@szunami thanks for addressing the warning messages.

Even I am not sure right now why the scaling and translation of the assets are messed up. I will have a look at it as soon as I get some time.

**Comment by krankur** [comment]
@szunami The changes in this PR look good. Merging them.

I am looking into the issues. Should be able to come up with a fix soon.

**Pull request merged**
